# netlify.toml
[build]
  command = "git submodule update --init --recursive && hugo --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.145.0"
  HUGO_ENV = "production"

# Correct baseURL in deploy previews and branch deploys
[context.deploy-preview]
  command = "hugo --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --minify -b $DEPLOY_URL"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"